version: '3.8'

services:
    dev:
        container_name: cash_flow_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        env_file:
            - .env
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - cash-flow-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

    cash-flow-mongo:
        image: mongo:5.0.3
        container_name: cash-flow-mongo
        volumes:
            - .docker-volumes/mongo:/data/db
        ports:
            - "27017:27017"
        networks:
            - cash-flow-network

networks:
    cash-flow-network: